"""Change metrics parsed from a run's stored unified diff (US-1.17).

Shared by db.complete_run (Python) so the frontend never re-implements the
area heuristic — it just reads the `area` field already stored per file.
"""

import re
from typing import Any

FRONTEND_MARKERS = ("apps/web/", "src/components/", "src/app/")
FRONTEND_EXTS = (".tsx", ".jsx", ".css", ".scss")
BACKEND_MARKERS = ("api/", "server/", "infra/")
BACKEND_EXTS = (".sql", ".py")

# us-109.3: nobody wrote these. A changeset that carries a dependency tree or a
# build output directory is still a legitimate changeset — the files really are
# in it — but counting them as authored lines makes every figure derived from
# `lines_added` meaningless. One run on 2026-08-09 landed 1,788,138 lines across
# 7,999 files (224 lines a file, the signature of a vendored tree) and became
# 98% of a workspace's reported 30-day output.
#
# Matched on whole path SEGMENTS, never substrings: `dist` as a substring also
# matches `redistribute/`, and silently discounting real work is the one failure
# mode worse than the bug being fixed.
VENDORED_DIRS = frozenset(
    {
        ".git",
        ".next",
        ".nuxt",
        ".turbo",
        ".venv",
        "__pycache__",
        "bower_components",
        "build",
        "coverage",
        "dist",
        "node_modules",
        "site-packages",
        "target",
        "vendor",
        "venv",
    }
)

# Generated by a package manager, not typed by anyone. Byte-for-byte
# deterministic from a manifest a human did write, which is the test.
VENDORED_FILES = frozenset(
    {
        "cargo.lock",
        "composer.lock",
        "gemfile.lock",
        "go.sum",
        "package-lock.json",
        "pnpm-lock.yaml",
        "poetry.lock",
        "uv.lock",
        "yarn.lock",
    }
)

VENDORED_SUFFIXES = (".min.js", ".min.css", ".map", ".lock.json")


def is_vendored(path: str) -> bool:
    """True when a path is machine-generated or third-party — dependency
    trees, build output, lockfiles, minified bundles and source maps."""
    lower = path.lower().strip()
    if not lower:
        return False
    segments = [s for s in lower.replace("\\", "/").split("/") if s]
    if not segments:
        return False
    # Directory segments only — a diff lists files, so the last segment is the
    # filename and is judged on its own terms below.
    if any(s in VENDORED_DIRS for s in segments[:-1]):
        return True
    basename = segments[-1]
    return basename in VENDORED_FILES or basename.endswith(VENDORED_SUFFIXES)


def classify_area(path: str) -> str:
    """vendored | frontend | backend | other, by path/extension heuristic.

    `vendored` is checked FIRST and is the only area excluded from a run's
    totals — `apps/web/node_modules/react/index.js` matches the frontend
    marker too, and whichever answer wins decides whether 1.8M lines count as
    somebody's work."""
    if is_vendored(path):
        return "vendored"
    lower = path.lower()
    if any(m in lower for m in FRONTEND_MARKERS) or lower.endswith(FRONTEND_EXTS):
        return "frontend"
    if any(m in lower for m in BACKEND_MARKERS) or lower.endswith(BACKEND_EXTS):
        return "backend"
    return "other"


def _file_path(lines: list[str]) -> str | None:
    for line in lines:
        if line.startswith("+++ "):
            p = line[4:].strip()
            if p != "/dev/null":
                return p[2:] if p.startswith("b/") else p
    for line in lines:
        if line.startswith("--- "):
            p = line[4:].strip()
            if p != "/dev/null":
                return p[2:] if p.startswith("a/") else p
    return None


def compute_diff_metrics(diff: str | None) -> dict[str, Any] | None:
    """Parse a stored unified diff into lines_added/removed, files_changed,
    and a per-file change_breakdown. None if there's no diff to parse —
    callers must leave the run's metric columns null, not 0.

    us-109.3: the three totals count AUTHORED files only. Vendored files stay
    in `change_breakdown` marked `area: "vendored"` — they were genuinely in
    the changeset, and dropping them would hide the thing that went wrong —
    but they do not count as anyone's output."""
    if not diff or not diff.strip():
        return None

    chunks = [c for c in re.split(r"(?m)^(?=diff --git )", diff) if c.strip()]
    if not chunks:
        return None

    per_file: dict[str, dict[str, int]] = {}
    order: list[str] = []
    for chunk in chunks:
        lines = chunk.splitlines()
        path = _file_path(lines) or lines[0].replace("diff --git ", "").strip()
        added = sum(1 for l in lines if l.startswith("+") and not l.startswith("+++"))
        removed = sum(1 for l in lines if l.startswith("-") and not l.startswith("---"))
        if path not in per_file:
            per_file[path] = {"added": 0, "removed": 0}
            order.append(path)
        per_file[path]["added"] += added
        per_file[path]["removed"] += removed

    breakdown = [
        {
            "path": p,
            "added": per_file[p]["added"],
            "removed": per_file[p]["removed"],
            "area": classify_area(p),
        }
        for p in order
    ]
    authored = [f for f in breakdown if f["area"] != "vendored"]
    return {
        "lines_added": sum(f["added"] for f in authored),
        "lines_removed": sum(f["removed"] for f in authored),
        "files_changed": len(authored),
        "change_breakdown": breakdown,
    }
